// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwoxhkntgqcnkoemozme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3b3hoa250Z3FjbmtvZW1vem1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1NDYyNjQsImV4cCI6MjA1NDEyMjI2NH0.eGxdVpAseb40XZD5XciWQYDDS4vplybS8MeyPdRuGqM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);